name: Typography
favicon: null
layout_spectrum: 0.24251
typography_spectrum: 0.68779
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5590b9'
    - '#2b2f32'
    - '#ede7da'
    - '#be494a'
    - '#c08068'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
